### PR TITLE
Fix #9: Correct off-by-one mistakes in "modulo 2" description.

### LINKED ISSUE #9: off-by-one problem
There are two off-by-one bugs at the end of "Boolean Algebra" section:

> A great use of the AND operator is to do a modulo of a number to a power of 2. For example, AND with 3 gets you a result between 0 and 2. AND with 7 gets you a result between 0 and 8.

### PR DESCRIPTION
**Pull request by snakeru**

### CODE REVIEW

**Comment by mschwartz** [comment]
GitHub is just git.  You fork the repo, create a branch, make changes, make a PR..

**Comment by mschwartz** [comment]
Thanks!

**Comment by snakeru** [comment]
> GitHub is just git. You fork the repo, create a branch, make changes, make a PR..

Umm... No, can't agree. "Make changes" is not really part of git - it's something that git always outsourced. Making a PR is even less so - git does have concept of changes, but it doesn't even have a concept of PR.

In any case - it's nice that at least such trivialities are solved for now.

**Comment by mschwartz** [comment]
https://docs.github.com/en/get-started/quickstart/contributing-to-projects?platform=mac

**Pull request merged**
